# Generated by Django 4.0.2 on 2022-02-23 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='category',
            field=models.CharField(default='general', max_length=30),
        ),
    ]
