# Generated by Django 4.0.2 on 2022-02-24 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_tracker', '0004_alter_transactions_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='category',
            field=models.CharField(choices=[('Income', 'Income'), ('Foods & Drink', 'Foods & Drink'), ('Shopping', 'Shopping'), ('Housing', 'Housing'), ('Transportation', 'Transporation'), ('Vehicle', 'Vehicle'), ('Entertainment', 'Entertainment'), ('Investment', 'Investment')], default='Income', max_length=30),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='type',
            field=models.BooleanField(choices=[(False, 'Expenses'), (True, 'Income')], default=False),
        ),
    ]
